Chieh H Chang (title:Network and Computer System Administrator) and a brief description:
- Establish a framework to achieve cost reduction, productivity, and end-user satisfaction.
- Measure program strengths and weaknesses, implementing changes as needed.
- Provide technical support to staff and faculty in over 10 departments.
- Manage daily technology tasks and coordinate projects with the Senior Technology Officer.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

